version: '3.4'

services:
  tms-nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 80:80
    depends_on:
      - tms-patient
    volumes:
      - /var/log/tms:/var/log/tms
      - /etc/ssl:/etc/ssl

  tms-eureka:
    build:
      context: .
      dockerfile: tms-eureka/dockerfile
    image: tms-eureka
    ports:
      - 8765:8765

  tms-config:
    build:
      context: .
      dockerfile: tms-config/dockerfile
    image: tms-config
    depends_on:
      - tms-eureka
    ports:
      - 8888:8888

  tms-db:
    build:
      context: .
      dockerfile: tms-db/dockerfile
    image: tms-db
    depends_on:
      - tms-config
      - tms-mongo
    ports:
      - 8080:8080

  tms-patient:
    build:
      context: .
      dockerfile: tms-patient/dockerfile
    image: tms-patient
    depends_on:
      - tms-db
    ports:
      - 8081:8081

  tms-mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/var/lib/mongo/data

volumes:
  mongo: {}
