server:
  port: 8888
spring:
  application:
    name: tms-config
  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri: git@github.com:shaart/3ms-clinic-config.git
          ignoreLocalSshSettings: true
          force-pull: true
          privateKey: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIJKgIBAAKCAgEA3wftGyqf5wq80ITX3YFT2W6pP0LmIGT2rZP2SeyTM/59Ueq7
            AsUsZ37PJPgt4ss3ptooXWGNItQx47Ud+0g4TXjlYxb+HEcg0tP1gqgAnNtewv1w
            pNx0cQ1hSqs+6KZ5WtuzgNkdVq+Ekojprzk/4qSs9gcY6X3dnMq7Hn9zoZDIgW9K
            ETZnOGx5QCbaEO2bPGfuDuwYL9BoB0m+rfm+K5ru1apDTtb1shGyz4KWunVwMD+O
            7TNR6P5VorTGFGKRanLkJc8hWLqkFYUA4Gfu4ZMHmOIOMTXrKZlZknYkikozv487
            lwoWM8neP9r7ySkP0rQT/wT7U77mlWYfhivXqVxnxIjBsch5dz1Fj//pav2xuBeA
            W9YTojKNRce2F/WO/9k0+DmbqKd2UHNjlLI7YVzgIySe9ckx7Bf31GkLE7TVDjKS
            XO5LJU6JAPp0i+rI2ebBk+93U+ZH6y2JWzPzNaSUWrNh+TMe2q1Pb6gpJ9oEJ8Di
            WwPqzTL9YQji+3MqvMllU1AEYuyPsa1X+euuyObKSJqPhE/4FwOhIhFF15zcZAmV
            JxLMpf7Yvu9qrmdF01hNrLjWgz0p4wXNaUt6tDko4uRMvBnL/2653yfIFVVoU2nZ
            /ufF7JLmNxsMryhd7DvBCddZtL4hsrzHG1wt5tOJ6h4hxV6W4XJHINPFqeUCAwEA
            AQKCAgBfk7D7hF+0DjjuDw/G3+ZD9pVXA99EoJ/JsO/JrDVFAdlIopPz0vV9gK1a
            hXR8jWPTAAhuRCDMfSzIDVTE26UtJhL/TNom2iBp2OWMUVy525SXcS61p7fKvtYj
            vpEd+EFnO2GIZQKapGrmtP+X1KvY/4MTh+UYIpU23PYlUq8F3NrgBQYzrCG931Zy
            tHOc74Yn883j3S9cRi5eeS7atXzWiPWy4N0pSxtNbSI4pRjc3Pjv5Dzmz6hZdazT
            Ji8Ai2EPwh6dSU9cC9fHVREUGdYYGv8VeEJmulmFoS7ugeyUysm0XLhHuM3c8bRp
            nvlpskwSmpM7JTJjKBr+iR4XTHCFWU0JX3BXNDnSInUoqJohrFS4jONNR72/3QZ4
            4znSDUlRY+3ruZl5/wEU1T29pou2aB5LJyFJDzIqf6+mmwdCB278vxDkMYE1p3lu
            DfLAXpInT1uSGOPAShFQMvVXx5VI/BhFCTJX+VNDbKOaIc5P5nuuEeV0DG8zFWhx
            E0GdIExxLDD/IdsWZ96sKZnV1Pjj44pFjmXTQ8ZL3YfsNQyTdcbE6E2+ua+q+oog
            KJWHA6aS2psacCjMxRK/H5j9vppnQ762O8x/YvWkz+n736scv/D3xUKi3Va+nvVg
            LyrE3Dv3CihjEN08nwgb+R3zgOuw6ETw8oh3hIYF1eauF0miXQKCAQEA/6XAjtJT
            Tj8ID41TOiOKtIFw5jPaSC54Rq0p33IrtxmkdZMQ9RAN6MjXes0ArcDxdKQ7maOe
            rJ3Zzk0aZeFKPFlzOTXkRw1afhj/Mq3h844aBLfONZ951nGg9RmeQN6NTwWKTlmT
            xfTrG5QUDv3T8TQur395CQQg8HTPQBRDKNicMAtt12JfG2Wv2b60gW8IsmFlcYxu
            TIt/1Y/pv3NG9BDU2iSfIYHsT0Dxoun12t4RdMaAM54rRu555thjp6USDBLSKZFr
            yOx5rqdHDiripBcSw2wQShId5MvlW6DSINyGdDgqaA0BjQm1wOQVufZHP/lXTBB/
            +tgReQMWX91UFwKCAQEA31ao654g74gHUU/SZofA7Ol2mq5NJpMDHr6FNWs+Qu48
            hd3BwQeTHsKVtVJvHdoE+CbfjduzIlikqSf+c7ytfWVRLVIyNR/rmrrm0G/uFva7
            rRt89t7nw33sxOMvLoUt6e67YUFyU9JJViVJl5RDtFllxTcKCIH9rikqYBhW+jYc
            sSPneALTLcYPDy9I8cIGu+7OiRnShOHOVmdluP173UmUY7DkoYV1IPLPizfZQIsZ
            +e78giC8ZOUUM2IZsB7UY+xhvZP9N7uxV9ejmPQNhTrU8WhAj9B77Q+55ur5c0/2
            owiXvdVStIAsvIAgLaHcxrF1icxqGw5SJfrtkSkjYwKCAQEAmyChcAkAtAJbidRg
            JG9cw5uoPohIdHR+V6TMO+Kz1C+jNBVBvPM4/YCiAMpVFxp1aioeYGSA7I38lMsE
            sb27plNBL/4bv2HC/7F7ae1JptkbwLEoWDGlZRMecJxTA1oItWLPQivpF74+zEVW
            xqIP8dWQXr4jW+09b6vx9xhUiHyoih7lUEVJIP7bbm3iaohN5rBjNjvY0mnz8Eub
            s6jn7UIpZxXB2jtUgeMOvaTqox0NyqaJNMlNyYT8Q7AbCKeKA/mHveGYXhvg2rJ2
            04oCbT/zCtKQL+I+cY+oZal42Kf4jp1mXi1GO6cguyOsa2OeaJuM9YMtpbFnKN9O
            vG05kQKCAQEAjd1BLXFjYGOaqla2wjQHIzXlBboj/ZWyjKved6EoimFEBpBnC5Mh
            K4/UgrnbJS4gq/QdWsGsVuvRpDVoVuIJnbZmyxAEHmSpRr7j8JC4vtN5QStNxI6w
            zyfE5wecJ8Om94qSceOdmIrh1JuY1HT0ULHciFo+wEq59g/l/+ZWEVegABFbbYr1
            04SUekPB5PcnSecWQFYruAarB41kOw6gyF59qJlrkQHx9bzmgns2P95b4Luin5Hl
            uX0dyMnOoWXj6Zj0OPSxCt7pdm/eVkDn+bH2I2XiZLe8kEfGAV1OmKW5d7P0lzvS
            7h7gy9fjGLlRQNDmZWJ4H7mICuIKV4O3GwKCAQEAtrHe1uHS/cAh6O2qIFEp3BR6
            H2RpgRFD0Kgpu4RrUBJPZemUdvA2qy17FwcqCJgiPOsDigrzlBasqWYLMq+nWECb
            bn/x6Xrt+JEtF5NVKQsr1HE2jwQHGzMqHsoxYD4F09D7MT+D9VqvdEO3wSBChCSc
            Xxtr8fymzGGS7J1XqpshF1YtvpEoDpPkG8GZExGOeqrTX11Vr7Ziwq38AKxTkS0w
            zhyfPKG8GskvZjcnwGbHugNifX3lOF9JhKcKWJxJwdP9960RPEfzbqgsluJmBW+j
            skdY+O/aqBRGJvQQAI14i+oUTzyO0Yg9itZtDROU0TnjYMZz1urtq/xgTLldiw==
            -----END RSA PRIVATE KEY-----

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    region: default
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8765/eureka